### ISSUE TITLE
mpeg header decoding fails

### ISSUE THREAD

**Issue by anudanan** [eriksl/streamproxy#13]
I´ve sometimes movies on my hdd in which the mpeg header can´t decode successfully.

I get an error in the message file
Apr  1 06:51:53 Wohnzimmer user.warn streamproxy: MpegTS::init: file length: 17430 Mb
Apr  1 06:51:53 Wohnzimmer user.warn streamproxy: MpegTS::init: invalid transport stream (no suitable pmt)

I´ve found out if I increase the timeout limit in this loop
https://github.com/eriksl/streamproxy/blob/e8ecbe2fd2745fab77701c4a5a3de1cdbca5461d/src/mpegts.cpp#L139

from 2000 to 4500 it works.
Do you know about a bug during decoding the mpeg header in the movie files or is it neccessary to increase the timeout value for some files?

I can send you the ts file if you want but it is a big file (18 GByte).
Maybe you only need a part from the beginning of the movie file.

**Comment by eriksl** [comment]
I bet these recordings are made using a VU+ Duo4k. Am I right?

**Comment by anudanan** [comment]
The movie was recorded with a uno4kse on the german VOX channel, not with Duo4k. Normally the trancoding works but with these movie only after changing the timeout

**Comment by eriksl** [comment]
Then maybe the Uno4kSE has the same bug as the Duo4k. Issue is the actual descrambling starts too late (sometimes even after several seconds, even though your softcam has setup the descrambler correctly). That means (a.o.) the first "recognisable" PMT may come after quite some time (in bytes). Normally, the PMT is repeated quite often, so streamproxy should not have to go out of it's lengths to find one.

**Comment by anudanan** [comment]
I understand. I have that not very often. Is it an ideae to increase the timeout value as a workaround? For me I have a solution with my own compiled streamproxy but if other users see the same problem than the workaround may fix the problem without  negativ effects. Or do you think there problems with a higher timeout value?

**Comment by eriksl** [comment]
I can increase the value, but only to the absolute minimum value required to get it working. It IS a workaround in the end.

**Comment by anudanan** [comment]
I know, it is your decision. Very often the manufactures don´t fix those bugs because during normal use (watching movies with the box) noone can see the bug. Normal playback with the box works fine.

**Comment by eriksl** [comment]
Please create PR. I am not very active for PLi at the moment.

**Comment by anudanan** [comment]
https://github.com/eriksl/streamproxy/pull/14

**Comment by anudanan** [comment]
Thx
