### ISSUE TITLE
streamproxy may use the first audio track and not the last one or it is configurable

### ISSUE THREAD

**Issue by anudanan** [eriksl/streamproxy#7]
From my point of view most movies with more than one audio track has the first audiotrack as the default one and not the last trace.

Streamproxy today takes the last audiotrack for transcoding
The best solution for that is to have a parameter in den conf file to select the audiostream 

A quick fix is to make a little change in encoder-broadcom.cpp to select the first track and not the last one

My idea it zo replace the code at line 68, 69 
```
		if(it->first == "audio")
			audio = it->second;
```

into
```

		if((audio == -1) && (it->first == "audio"))
			audio = it->second;

```

**Comment by eriksl** [comment]
It takes the first audio stream UNLESS it's a narrative track, identified by metadata or having "nar" in the id.
 
The only other way to properly solve this is to have streamproxy completely parse lamedb. I'd rather spend the time on moving the code to enigma then.
